services:
  - type: web
    name: zargo-backend
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
